name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-18.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.10.4
              otp: 21.3.8.21
          - pair:
              elixir: 1.11.4
              otp: 23.3.3
          - pair:
              elixir: 1.12.0
              otp: 24.0.0
            lint: lint
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        name: Set up Elixir
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
      - name: Quality checks
        run: mix quality
